controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

usuarios_formulario:
    path: /usuarios/formulario
    controller: App\Controller\UsuariosController::formulario

register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_logout:
    path: /logout

app_usuarios_show:
    path: '/usuarios/{id}'
    controller: 'App\Controller\UsuariosController::show'

app_usuarios_edit:
    path: '/usuarios/editar/{id}'
    controller: 'App\Controller\UsuariosController::edit'
    