controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

usuarios_formulario:
    path: /usuarios/formulario
    controller: App\Controller\UsuariosController::formulario

register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_logout:
    path: /logout



    